"""Initial migration.

Revision ID: acb1908beb9b
Revises: 
Create Date: 2023-11-12 04:45:16.932166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acb1908beb9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
